language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'
    - 'client/node_modules'
    - 'client/node'

script:
- ./mvnw package -e
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -f target/docker/Dockerfile -t $DOCKER_USERNAME/eagle-eye:latest target
- docker images
- docker push $DOCKER_USERNAME/eagle-eye:latest
