version: '2'
services:

  build-client:
      build:
        context: ./client
        dockerfile: Dockerfile.build-client
      volumes:
        - dist:/dist

  serve:
      image: nginx
      ports:
        - "127.0.0.1:80:80"
      depends_on:
        - build-client
      volumes:
        - dist:/usr/share/nginx/html:ro

volumes:
   dist:
